#!/usr/bin/env bash
#
# create-teams-app-package.sh
#
# Generates a Teams App manifest.json from app requirements and branding
# metadata, bundles it with icon files, and creates a ZIP package ready
# for upload to Teams Admin Center.
#
# Usage:
#   ./create-teams-app-package.sh --bot-app-id <GUID> [OPTIONS]
#
# Inputs:
#   --bot-app-id     The Entra ID app registration client ID for the bot (required)
#   --requirements   Path to app-requirements.json (default: ../src/TeamsNotificationBot/app-requirements.json)
#   --metadata       Path to app-metadata.json (default: ./app-metadata.json)
#
# The requirements file is generated by: scripts/generate-requirements.sh
# The metadata contains branding/manifest fields maintained manually.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Defaults ---
ICONS_DIR="${SCRIPT_DIR}"
OUTPUT_DIR="${SCRIPT_DIR}"
REQUIREMENTS_FILE="${SCRIPT_DIR}/../src/TeamsNotificationBot/app-requirements.json"
METADATA_FILE="${SCRIPT_DIR}/app-metadata.json"
BOT_APP_ID=""
DRY_RUN=false

# --- Usage ---
usage() {
  cat <<EOF
Usage: $(basename "$0") --bot-app-id <GUID> [OPTIONS]

Generate a Teams App manifest.json and ZIP package from app requirements
and branding metadata.

Required:
  --bot-app-id <GUID>    Entra ID app registration client ID for the bot

Options:
  --requirements <path>  Path to app-requirements.json (default: ../src/TeamsNotificationBot/app-requirements.json)
  --metadata <path>      Path to app-metadata.json (default: ./app-metadata.json)
  --output-dir <dir>     Directory for output files (default: script directory)
  --icons-dir  <dir>     Directory containing color.png and outline.png (default: script directory)
  --dry-run              Generate manifest.json only, skip ZIP creation
  -h, --help             Show this help message
EOF
  exit 0
}

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      ;;
    --bot-app-id)
      BOT_APP_ID="$2"
      shift 2
      ;;
    --requirements)
      REQUIREMENTS_FILE="$2"
      shift 2
      ;;
    --metadata)
      METADATA_FILE="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --icons-dir)
      ICONS_DIR="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -*)
      echo "Error: Unknown option '$1'" >&2
      echo "" >&2
      usage
      ;;
    *)
      echo "Error: Unexpected argument '$1'" >&2
      echo "" >&2
      usage
      ;;
  esac
done

if [[ -z "${BOT_APP_ID}" ]]; then
  echo "Error: --bot-app-id is required." >&2
  echo "" >&2
  usage
fi

# --- Validate prerequisites ---
if ! command -v jq &>/dev/null; then
  echo "Error: 'jq' is required but not installed. Install with: sudo apt install jq" >&2
  exit 1
fi

if ! command -v zip &>/dev/null; then
  echo "Error: 'zip' is required but not installed. Install with: sudo apt install zip" >&2
  exit 1
fi

if [[ ! -f "${REQUIREMENTS_FILE}" ]]; then
  echo "Error: Requirements file not found: ${REQUIREMENTS_FILE}" >&2
  echo "  Generate it with: cd scripts && bash generate-requirements.sh" >&2
  exit 1
fi

if [[ ! -f "${METADATA_FILE}" ]]; then
  echo "Error: Metadata file not found: ${METADATA_FILE}" >&2
  exit 1
fi

# --- Read and validate inputs ---
echo "Reading requirements: ${REQUIREMENTS_FILE}"
echo "Reading metadata:     ${METADATA_FILE}"

# Validate required requirements fields
for field in notifier_application_version teams_app_configuration teams_app_command_lists; do
  if ! jq -e ".${field}" "${REQUIREMENTS_FILE}" &>/dev/null; then
    echo "Error: Required field '${field}' missing in requirements." >&2
    exit 1
  fi
done

# Validate required metadata fields
REQUIRED_META=(short_name full_name description_short description_full developer_name developer_website privacy_url terms_url accent_color output_zip)
for field in "${REQUIRED_META[@]}"; do
  value=$(jq -r ".${field} // empty" "${METADATA_FILE}")
  if [[ -z "${value}" ]]; then
    echo "Error: Required field '${field}' missing or empty in metadata." >&2
    exit 1
  fi
done

# Print summary
APP_VERSION=$(jq -r '.notifier_application_version' "${REQUIREMENTS_FILE}")
SHORT_NAME=$(jq -r '.short_name' "${METADATA_FILE}")
OUTPUT_ZIP=$(jq -r '.output_zip' "${METADATA_FILE}")
IS_NOTIFICATION_ONLY=$(jq -r '.teams_app_configuration.is_notification_only' "${REQUIREMENTS_FILE}")
SCOPES=$(jq -c '.teams_app_configuration.scopes' "${REQUIREMENTS_FILE}")
SUPPORTS_CHANNEL_FEATURES=$(jq -r '.teams_app_configuration.supports_channel_features // empty' "${REQUIREMENTS_FILE}")

echo ""
echo "  Bot App ID:        ${BOT_APP_ID}"
echo "  App Name:          ${SHORT_NAME}"
echo "  Version:           ${APP_VERSION}"
echo "  Notification Only: ${IS_NOTIFICATION_ONLY}"
echo "  Scopes:            ${SCOPES}"
echo "  Output ZIP:        ${OUTPUT_ZIP}"

# --- Validate icon files ---
COLOR_ICON="${ICONS_DIR}/color.png"
OUTLINE_ICON="${ICONS_DIR}/outline.png"

if [[ ! -f "${COLOR_ICON}" ]]; then
  echo "Error: Color icon not found: ${COLOR_ICON}" >&2
  echo "  Expected 192x192 PNG file." >&2
  exit 1
fi

if [[ ! -f "${OUTLINE_ICON}" ]]; then
  echo "Error: Outline icon not found: ${OUTLINE_ICON}" >&2
  echo "  Expected 32x32 transparent PNG file." >&2
  exit 1
fi

echo "  Icons:             color.png, outline.png"

# --- Generate manifest.json ---
MANIFEST_PATH="${OUTPUT_DIR}/manifest.json"

# Merge requirements + metadata + bot-app-id into Teams manifest.
# The jq expression IS the template — it handles conditional JSON (commandLists,
# supportsChannelFeatures) and array merging that a sed-based template can't.
jq -n \
  --arg bot_app_id "${BOT_APP_ID}" \
  --arg supports_channel_features "${SUPPORTS_CHANNEL_FEATURES}" \
  --argjson reqs "$(cat "${REQUIREMENTS_FILE}")" \
  --argjson metadata "$(cat "${METADATA_FILE}")" \
  '{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.25/MicrosoftTeams.schema.json",
    "manifestVersion": "1.25",
    "version": $reqs.notifier_application_version,
    "id": $bot_app_id,
    "name": {
      "short": $metadata.short_name,
      "full": $metadata.full_name
    },
    "description": {
      "short": $metadata.description_short,
      "full": $metadata.description_full
    },
    "icons": {
      "outline": "outline.png",
      "color": "color.png"
    },
    "developer": {
      "name": $metadata.developer_name,
      "websiteUrl": $metadata.developer_website,
      "privacyUrl": $metadata.privacy_url,
      "termsOfUseUrl": $metadata.terms_url
    },
    "accentColor": $metadata.accent_color,
    "bots": [
      ({
        "botId": $bot_app_id,
        "scopes": $reqs.teams_app_configuration.scopes,
        "supportsFiles": ($reqs.teams_app_configuration.supports_files // false),
        "isNotificationOnly": $reqs.teams_app_configuration.is_notification_only
      } + if ($reqs.teams_app_command_lists | length) > 0 then { "commandLists": $reqs.teams_app_command_lists } else {} end)
    ],
    "permissions": ["identity"],
    "validDomains": []
  } + if $supports_channel_features != "" then { "supportsChannelFeatures": $supports_channel_features } else {} end' > "${MANIFEST_PATH}"

echo ""
echo "Generated: ${MANIFEST_PATH}"

if ${DRY_RUN}; then
  echo ""
  echo "Dry run — skipping ZIP creation."
  echo "Manifest content:"
  cat "${MANIFEST_PATH}"
  exit 0
fi

# --- Create ZIP package ---
mkdir -p "${OUTPUT_DIR}"
ZIP_PATH="${OUTPUT_DIR}/${OUTPUT_ZIP}"

# Remove existing ZIP if present
rm -f "${ZIP_PATH}"

# Create ZIP from temp directory with all required files at the root
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "${TEMP_DIR}"' EXIT

cp "${MANIFEST_PATH}" "${TEMP_DIR}/manifest.json"
cp "${COLOR_ICON}" "${TEMP_DIR}/color.png"
cp "${OUTLINE_ICON}" "${TEMP_DIR}/outline.png"

(cd "${TEMP_DIR}" && zip -q "${ZIP_PATH}" manifest.json color.png outline.png)

echo ""
echo "Created ZIP package: ${ZIP_PATH}"
echo ""
echo "ZIP contents:"
unzip -l "${ZIP_PATH}"
echo ""
echo "Next steps:"
echo "  1. Upload ${OUTPUT_ZIP} to Teams Admin Center > Teams apps > Manage apps"
echo "  2. Or: Teams client > Apps > Manage your apps > Upload an app to your org's app catalog"
