#!/usr/bin/env bash
#
# generate-requirements.sh
#
# Scans the app source code to extract code-derived values (queues, routes,
# runtime version, auth role, messaging endpoint), merges them with the static
# seed file, computes an infrastructure requirements hash fingerprint, and
# produces src/TeamsNotificationBot/app-requirements.json — the machine-readable
# declaration of what this app version needs from infrastructure and manifest.
#
# Usage:
#   bash generate-requirements.sh [--seed <path>] [--output <path>]
#
# Defaults:
#   --seed    ./requirements-static.json
#   --output  ../src/TeamsNotificationBot/app-requirements.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="${SCRIPT_DIR}/../src/TeamsNotificationBot"

# --- Defaults ---
SEED_FILE="${SCRIPT_DIR}/requirements-static.json"
OUTPUT_FILE="${APP_DIR}/app-requirements.json"

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed)    SEED_FILE="$2"; shift 2 ;;
    --output)  OUTPUT_FILE="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $(basename "$0") [--seed <path>] [--output <path>]"
      echo "  --seed    Path to requirements-static.json (default: ./requirements-static.json)"
      echo "  --output  Path to output requirements (default: ../src/TeamsNotificationBot/app-requirements.json)"
      exit 0
      ;;
    *)
      echo "Error: Unknown option '$1'" >&2
      exit 1
      ;;
  esac
done

# --- Validate prerequisites ---
if ! command -v jq &>/dev/null; then
  echo "Error: 'jq' is required. Install with: sudo apt install jq" >&2
  exit 1
fi

if [[ ! -f "${SEED_FILE}" ]]; then
  echo "Error: Seed file not found: ${SEED_FILE}" >&2
  exit 1
fi

if [[ ! -d "${APP_DIR}" ]]; then
  echo "Error: App directory not found: ${APP_DIR}" >&2
  exit 1
fi

echo "Generating app requirements..."
echo "  Seed:   ${SEED_FILE}"
echo "  App:    ${APP_DIR}"
echo "  Output: ${OUTPUT_FILE}"

# --- Extract code-derived values ---

# Queues: QueueTrigger("name") in Functions/*.cs
QUEUES=$(grep -rohP 'QueueTrigger\("\K[^"]+' "${APP_DIR}/Functions/"*.cs \
  | sort -u \
  | jq -Rn '[inputs]')
echo "  Queues: ${QUEUES}"

# Alert route: Route = "v1/alert/{alias}" in AlertFunction.cs
ALERT_ROUTE="/api/$(grep -ohP 'Route\s*=\s*"\K[^"]+' "${APP_DIR}/Functions/AlertFunction.cs" | head -1)"
echo "  Alert route: ${ALERT_ROUTE}"

# Bot messaging endpoint: Route = "messages" in BotMessagesFunction.cs
MESSAGING_ENDPOINT="/api/$(grep -ohP 'Route\s*=\s*"\K[^"]+' "${APP_DIR}/Functions/BotMessagesFunction.cs" | head -1)"
echo "  Messaging endpoint: ${MESSAGING_ENDPOINT}"

# Required role from AuthMiddleware.cs
REQUIRED_ROLE=$(grep -oP 'RequiredRole\s*=\s*"\K[^"]+' "${APP_DIR}/Middleware/AuthMiddleware.cs")
echo "  Required role: ${REQUIRED_ROLE}"

# .NET version from .csproj
DOTNET_VERSION=$(grep -oP '<TargetFramework>net\K[^<]+' "${APP_DIR}"/*.csproj | head -1)
echo "  .NET: ${DOTNET_VERSION}"

# App version from AppInfo.cs
APP_VERSION=$(grep -oP 'Version\s*=\s*"\K[^"]+' "${APP_DIR}/Helpers/AppInfo.cs")
echo "  Version: ${APP_VERSION}"

# --- Merge seed + code-derived into requirements (without infra hash) ---
TEMP_FILE=$(mktemp)
trap 'rm -f "${TEMP_FILE}"' EXIT

jq -n \
  --argjson seed "$(cat "${SEED_FILE}")" \
  --argjson queues "${QUEUES}" \
  --arg alert_route "${ALERT_ROUTE}" \
  --arg messaging_endpoint "${MESSAGING_ENDPOINT}" \
  --arg required_role "${REQUIRED_ROLE}" \
  --arg dotnet_version "${DOTNET_VERSION}" \
  --arg app_version "${APP_VERSION}" \
  --arg repo_url "https://github.com/dsb-norge/teams-notifier-function-app" \
  '{
    _generated: "This file is generated by scripts/generate-requirements.sh. Do not edit manually.",
    _description: "Requirements for Azure infrastructure and Teams configuration for the Teams Notifier application.",
    _created_by: $repo_url,
    notifier_application_version: $app_version,
    function_app_runtime_version: $dotnet_version,
    storage_account_required_queues: $queues,
    well_known_routes: {
      azure_alert_webhook_receiver_endpoint: $alert_route
    },
    function_app_required_app_settings: $seed.function_app_required_app_settings,
    bot_auth_settings: ($seed.bot_auth_settings + { required_role: $required_role }),
    bot_service: ($seed.bot_service + { messaging_endpoint: $messaging_endpoint }),
    teams_app_configuration: $seed.teams_app_configuration,
    teams_app_command_lists: $seed.teams_app_command_lists
  }' > "${TEMP_FILE}"

# --- Compute infrastructure_requirements_unique_hash from TF-consumed fields ---
INFRA_HASH=$(jq -S '{function_app_runtime_version, storage_account_required_queues, well_known_routes, function_app_required_app_settings, bot_auth_settings, bot_service}' "${TEMP_FILE}" \
  | sha256sum | cut -c1-12)
echo "  Infra hash: ${INFRA_HASH}"

# --- Inject hash and write final output ---
jq --arg hash "${INFRA_HASH}" \
  '{_generated, _description, _created_by, notifier_application_version, infrastructure_requirements_unique_hash: $hash, function_app_runtime_version, storage_account_required_queues, well_known_routes, function_app_required_app_settings, bot_auth_settings, bot_service, teams_app_configuration, teams_app_command_lists}' \
  "${TEMP_FILE}" > "${OUTPUT_FILE}"

echo ""
echo "Requirements generated: ${OUTPUT_FILE}"
