#!/usr/bin/env bash
#
# generate-contract.sh
#
# Scans the app source code to extract code-derived values (queues, tables,
# routes, versions), merges them with the static seed file, and produces
# src/TeamsNotificationBot/app-contract.json — the single contract
# describing the app's infrastructure requirements.
#
# Usage:
#   bash generate-contract.sh [--seed <path>] [--output <path>]
#
# Defaults:
#   --seed    ./contract-seed.json
#   --output  ../src/TeamsNotificationBot/app-contract.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="${SCRIPT_DIR}/../src/TeamsNotificationBot"

# --- Defaults ---
SEED_FILE="${SCRIPT_DIR}/contract-seed.json"
OUTPUT_FILE="${APP_DIR}/app-contract.json"

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed)    SEED_FILE="$2"; shift 2 ;;
    --output)  OUTPUT_FILE="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $(basename "$0") [--seed <path>] [--output <path>]"
      echo "  --seed    Path to contract-seed.json (default: ./contract-seed.json)"
      echo "  --output  Path to output contract (default: ../app/app-contract.json)"
      exit 0
      ;;
    *)
      echo "Error: Unknown option '$1'" >&2
      exit 1
      ;;
  esac
done

# --- Validate prerequisites ---
if ! command -v jq &>/dev/null; then
  echo "Error: 'jq' is required. Install with: sudo apt install jq" >&2
  exit 1
fi

if [[ ! -f "${SEED_FILE}" ]]; then
  echo "Error: Seed file not found: ${SEED_FILE}" >&2
  exit 1
fi

if [[ ! -d "${APP_DIR}" ]]; then
  echo "Error: App directory not found: ${APP_DIR}" >&2
  exit 1
fi

echo "Generating app contract..."
echo "  Seed:   ${SEED_FILE}"
echo "  App:    ${APP_DIR}"
echo "  Output: ${OUTPUT_FILE}"

# --- Extract code-derived values ---

# Queues: QueueTrigger("name") in Functions/*.cs
QUEUES=$(grep -rohP 'QueueTrigger\("\K[^"]+' "${APP_DIR}/Functions/"*.cs \
  | sort -u \
  | jq -Rn '[inputs]')
echo "  Queues: ${QUEUES}"

# Tables: new TableClient(..., "name") in Program.cs
TABLES_PROGRAM=$(grep -ohP 'new TableClient\([^,]+,\s*"\K[^"]+' "${APP_DIR}/Program.cs" \
  | sort -u)

# Tables: AzureTableCounterStore(..., "name") in Program.cs
TABLES_COUNTER=$(grep -ohP 'AzureTableCounterStore\([^,]+,\s*"\K[^"]+' "${APP_DIR}/Program.cs" \
  | sort -u)

TABLES=$(printf '%s\n' ${TABLES_PROGRAM} ${TABLES_COUNTER} | sort -u | jq -Rn '[inputs]')
echo "  Tables: ${TABLES}"

# Routes: Route = "path" in Functions/*.cs
ROUTES_RAW=$(grep -rohP 'Route\s*=\s*"\K[^"]+' "${APP_DIR}/Functions/"*.cs \
  | sort -u)

# Build route map: key = last non-parameter segment (special-case "messages" -> "bot_messages")
ROUTES=$(echo "${ROUTES_RAW}" | while IFS= read -r route; do
  # Derive key: take last segment that doesn't start with {
  key=$(echo "${route}" | tr '/' '\n' | grep -v '^{' | tail -1)
  # Special case: "messages" route is the bot endpoint
  if [[ "${key}" == "messages" ]]; then
    key="bot_messages"
  fi
  # Special case: openapi.yaml -> openapi
  key="${key%.yaml}"
  echo "${key}|/api/${route}"
done | jq -Rn '
  [inputs | split("|")] |
  reduce .[] as $pair ({}; .[$pair[0]] = $pair[1])
')
echo "  Routes: $(echo "${ROUTES}" | jq -c '.')"

# .NET version from .csproj
DOTNET_VERSION=$(grep -oP '<TargetFramework>net\K[^<]+' "${APP_DIR}"/*.csproj | head -1)
echo "  .NET:   ${DOTNET_VERSION}"

# Functions runtime version from .csproj
FUNCTIONS_RUNTIME=$(grep -oP '<AzureFunctionsVersion>\K[^<]+' "${APP_DIR}"/*.csproj | head -1)
echo "  Runtime: ${FUNCTIONS_RUNTIME}"

# App version from AppInfo.cs
APP_VERSION=$(grep -oP 'Version\s*=\s*"\K[^"]+' "${APP_DIR}/Helpers/AppInfo.cs")
echo "  Version: ${APP_VERSION}"

# --- Merge seed + code-derived into contract ---
jq -n \
  --argjson seed "$(cat "${SEED_FILE}")" \
  --argjson queues "${QUEUES}" \
  --argjson tables "${TABLES}" \
  --argjson routes "${ROUTES}" \
  --arg dotnet_version "${DOTNET_VERSION}" \
  --arg functions_runtime "${FUNCTIONS_RUNTIME}" \
  --arg app_version "${APP_VERSION}" \
  '{
    _generated: "This file is generated by scripts/generate-contract.sh. Do not edit manually.",
    version: $app_version,
    runtime: {
      dotnet: $dotnet_version,
      functions: $functions_runtime
    },
    queues: $queues,
    tables: $tables,
    routes: $routes,
    env_vars: $seed.env_vars,
    easyauth: $seed.easyauth,
    bot: $seed.bot,
    command_lists: $seed.command_lists
  }' > "${OUTPUT_FILE}"

echo ""
echo "Contract generated: ${OUTPUT_FILE}"
